"use client"
import { useState, useEffect } from 'react';
import { usePathname } from 'next/navigation';
import { AuthProvider, useAuth } from "../context/AuthContext";

import { Collapse, Layout, theme } from 'antd';
const { Content } = Layout;
import Sider from './../components/Sider';
import Header from './../components/Header';
import styles from './../../styles.module.css';

const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};
// import localFont from 'next/font/local'
export default function RootLayout({ children }) {
  const pathname = usePathname();
  const [collapsed, setCollapsed] = useState(false);
  const { user } = useAuth()

  const toggleCollapse = () => {
    setCollapsed(!collapsed)
  }

  useEffect(() => {
    const handleResize = () => {
      if (window.innerWidth <= 1200) {
        setCollapsed(true); // Automatically collapse when width is <= 800px
      } else {
        setCollapsed(false); // Expand when width is > 800px
      }
    };

    // Add the resize event listener
    window.addEventListener('resize', handleResize);

    // Run the resize handler once to initialize
    handleResize();

    // Cleanup the event listener on component unmount
    return () => {
      window.removeEventListener('resize', handleResize);
    };
  }, []);

  return (
    <div style={{ margin: '0', fontFamily: 'font' }}>
      {user ?
        <>
          <Layout style={{ height: '100vh', overflow: 'hidden' }}>
            {/* fix collapse passing attribute to make it work again */}
            <Sider collapsed={collapsed} style={{
              position: 'sticky',
              top: 0,
              height: '100vh', // Ensures it fills the full height
              overflow: 'auto', // Allows scrolling inside if needed
            }} />
            <Layout style={{ background: 'F5F7F8' }}>
              <Header toggleCollapse={toggleCollapse} collapsed={collapsed} />
              <Content
                style={{ margin: '25px' }}
              // className={styles.containerC}
              >
                {children}
              </Content>
            </Layout>
          </Layout>
        </> : children
      }
    </div>
  );
}
